apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nzhussup/data_management:latest
          env:
            - name: DATABASE_HOST
              value: "db-service"
            - name: DATABASE_PORT
              value: "5555"
          ports:
            - containerPort: 4444

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
  type: NodePort
