name: Model API Testing and Docker Build/Push CI

on:
  push:
    paths:
      - "services/model_api_service/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: services/model_api_service
        run: |
          pip install --no-cache-dir --upgrade -r requirements.txt wheel

      - name: Install custom dependencies
        working-directory: services/model_api_service
        run: |
          pip install --no-cache-dir -i https://test.pypi.org/simple/ -r requirements_testpypi.txt --extra-index-url https://pypi.org/simple/

      - name: Run tests
        working-directory: services/model_api_service
        run: |
          pytest tests

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        working-directory: services/model_api_service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/model_api:latest .

      - name: Push Docker image
        working-directory: services/model_api_service
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/model_api:latest
