name: Build and Push Docker Image

on:
  push:
    paths:
      - 'services/model_api_service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        working-directory: services/model_api_service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/model_api:latest .

      - name: Push Docker image
        working-directory: services/model_api_service
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/model_api:latest

