name: Model Package Testing, Build/Push CI

on:
  push:
    paths:
      - "packages/model_train/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        working-directory: packages/model_train
        run: |
          python3 -m pip install --upgrade build
          pip3 install .

      - name: Run tests
        working-directory: packages/model_train
        run: |
          pytest tests

  build-and-publish:
    needs: [setup, test]
    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        working-directory: packages/model_train
        run: |
          python3 -m pip install --upgrade build twine

      - name: Create .pypirc file
        run: |
          echo "[distutils]" > ~/.pypirc
          echo "index-servers =" >> ~/.pypirc
          echo "    testpypi" >> ~/.pypirc
          echo "" >> ~/.pypirc
          echo "[testpypi]" >> ~/.pypirc
          echo "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
          echo "username = __token__" >> ~/.pypirc
          echo "password = ${{ secrets.TESTPYPI_TOKEN }}" >> ~/.pypirc

      - name: Build the package
        working-directory: packages/model_train
        run: |
          python3 -m build

      - name: Publish package to TestPyPI
        working-directory: packages/model_train
        run: |
          python3 -m twine upload --repository testpypi dist/*
